DBCC CHECKIDENT ('[Movie]', RESEED, 0);
DBCC CHECKIDENT ('[Genre]', RESEED, 0);
DBCC CHECKIDENT ('[Director]', RESEED, 0);
DBCC CHECKIDENT ('[User]', RESEED, 0);
DBCC CHECKIDENT ('[Rental]', RESEED, 0);
GO